# 生成器

这里不在解释什么是生成器以及生生成器的原理，主要是生成器的使用和方法

###一.最简单的生成器

```python
(i for i in range(3))
```

#### 1.yield 语句的用法总结

结构：

```python
temp = yield 表达式(每次迭代要返回的值）
```

如果要返回确定的值，后面的表达式不可省略，绝大部分情况下我们也不省略，否则只能返回 None；

**如果使用了 send(value)。传递进去的那个 value 回取代那个表达式的值，** 并且会将传递进去的那个值返回给 yield 表达式的结果 temp，所以如果想在 yield 后面使用传递进去的那个值，必须要有使用 temp，否则无法使用；

### 二.send 方法

```python
def new_generator(n):
    for i in range(n):
        temp = yield i
        print(f"我是{temp}")


g = new_generator(5)
print(next(g))  # 输出0, 我是None
print(next(g))  # 输出1, 我是None
print(g.send(100))  # 输出2, 我是100, 将100 通过send传到temp
print(next(g))  # 输出3, 我是None
print(next(g))  # 输出4, 我是None
```

从上面可以看出 yield 语句与普通函数的 return 语句的区别在哪里了，主要集中在以下几点

1.return 不能写成“temp=return xxxx”的形式，会提示语法错误，但是 yield 可以写成“temp=yield xxxx”的形式；

2.普通函数 return 后面的语句都是不会再执行的，但是 yield 语句后面的依然会执行，但是需要注意的是，由于“延迟加载”特性，yield 后面的代码并不是在第一次迭代的时候执行的，而是第二次迭代的时候才执行第一次 yield 后面没有执行的代码。也正是这个特性，构成了 yield 为什么是实现协程的最简单实现。

3.使用 send()方法传进去的值，实际上就是 yield 表达式返回的值，这就是为什么前面每次输出 print(temp)都打印出 None，因为没有 send 值，所以 temp 为 None，但是 send(100)之后却打印 100，因为此时 temp 就是 100 了。

#### 1.send(arg)方法总结

它的主要作用是，当我需要手动更改生成器里面的某一个值并且使用它，则 send 发送进去一个数据，然后保存到 yield 语句的返回值，以提供使用。

send(arg)的返回值就是那个本来应该被迭代出来的那个值。 这样既可以保证我能够传入新的值，原来的值也不会弄丢。

### 三.throw 方法

在生成器中抛出异常，并且这个 throw 函数会返回下一个要迭代的值或者是 StopIteration。

```python
def throw_generator():
    yield 'a'
    yield 'b'
    yield 'c'


g = throw_generator()
print(next(g))  # a
print(next(g))  # b
print('-------------------------')
print(g.throw(StopIteration))  # StopIteration
print(next(g))
```

因为在迭代完 b 之后，就触发了 StopIteration 异常，这相当于后面的 ‘c’ 已经没用了，跳过了 c ,c 再也不会执行，就中断了，所以后面的 'c'再也不会迭代，所以这里不会再返回任何值，返回的是 StopIteration。

再看一个例子

```python
def throw_generator():
    try:
        yield 'a'
        yield 'b'
        yield 'c'
        yield 'd'
        yield 'e'
    except ValueError:
        print('触发“ValueError"了')
    except TypeError:
        print('触发“TypeError"了')


g = throw_generator()
print(next(g))  # a
print(next(g))  # b
print('-------------------------')
print(g.throw(ValueError))  # 触发“ValueError"了”，奔溃报StopIteration错误
print('-------------------------')
print(next(g))
print(next(g))
print('-------------------------')
print(g.throw(TypeError))
print('-------------------------')
print(next(g))
```

当前面两次执行了 a 和 b 之后，向生成器扔进去一个异常，触发 ValueError 异常，这时候意味着 try 后面的 c、d、e 已经作废了，不会再有用，这个生成器已经终止了，因此 g.throw()会返回 StopIteration。

再看一个例子：

```python
def my_generator():
    while True:
        try:
            yield 'a'
            yield 'b'
            yield 'c'
            yield 'd'
            yield 'e'
        except ValueError:
            print('触发“ValueError"了')
        except TypeError:
            print('触发“TypeError"了')


g = my_generator()
print(next(g))  # a
print(next(g))  # b
print('-------------------------')
print(g.throw(ValueError))  # 触发“ValueError"了 a
print('-------------------------')
print(next(g))  # b
print(next(g))  # c
print('-------------------------')
print(g.throw(TypeError))  # 触发“TypeError"了 a
print('-------------------------')
print(next(g))  # b
```

首先 print(next(g))两次：会输出 a、b，并停留在 c 之前。

然后由于执行了 g.throw(ValueError)，所以会跳过所有后续的 try 语句，也就是说 yield 'c'、yield 'd'、yield 'e'不会被执行，

然后进入到 except 语句，打印出 触发“ValueError"了。

然后再次进入到 while 语句部分，消耗一个 yield，此时因为是重新进入的 while，小号的依然是第一个 yield 'a'，所以会输出 a。实际上这里的 a 也就是 g.throw()的返回值，因为它返回的是下一个迭代的数；

然后在 print(next(g))两次，会执行 yield b’、yield 'c’语句，打印出 b、c，并停留在执行完该语句后的位置，即 yield 'd'之前。

然后再 g.throw(TypeError)：会跳出 try 语句，从而后面的 d,e 不会被执行，下次自一次进入 while，依然打印出 a。最后，执行了一次 print(next(g))，打印出 b。

### 四.生成器启动关闭

#### 1.启动

启动生成器，启动的两种方法为：
第一：直接使用 next(g)，这会直接开始迭代第一个元素（推荐使用这个启动）
第二：使用 g.send(None)进行启动，注意第一次启动的时候只能传入 None，如果传入其他具体的指则会报错哦！

```python
def throw_generator():
    yield 1
    yield 2
    yield 3
    yield 4


g = throw_generator()
print(g.send(None))
print(next(g))
print(next(g))
```

#### 2.关闭

使用 close()方法

如果一个生成器被中途关闭之后，在此调用 next()方法，则会显示错误

```python
def my_generator():
    yield 1
    yield 2
    yield 3
    yield 4


g = my_generator()
print(next(g))
print(next(g))
g.close()
print(next(g))  # 在此处会显示错误
```

#### 五.终止迭代

关闭生成器，使用 close()方法，后面的迭代或抛出 StopIteration 异常。另外

在一个生成器中，如果没有 return，则默认执行到函数完毕时返回 StopIteration

```python
def g1():
    yield 1
g=g1()
next(g)
next(g)
```

如果在执行过程中 return，则直接抛出 StopIteration 终止迭代。

```python
def g2():
    yield 'a'
    return
    yield 'b'

g=g2()
next(g)
next(g)
```

如果在 return 后返回一个值，那么这个值为 StopIteration 异常的说明，不是程序的返回值。

```python
def g3():
    yield 'a'
    return '这是错误说明'
    yield 'b'

g=g3()
next(g)
next(g)
```

> 注意：
>
> 生成器没有办法使用 return 来返回值。因为 return 返回的那个值是通过 StopIteration 的异常信息返回的，所以我没办法直接获取这个 return 返回的值。
>
> 当然上面所说的无法获取 return 返回值，我们指的是没有办法通过 result=g3()这种形式获取 return 的返回值。
>
> 实际上还是可以获取这个 return 的值的，有两种方法：
> 方法一：使用后面的 yield from 语句
> 方法二： 因为 return 返回的值是作为 StopIteration 的一个 value 属性存在的，StopIteration 本质上是一个类，所以可以通过访问它的 value 属性获取这个 return 返回的值。使用下面的代码：

```python
def g3():
    yield 'a'
    return '这是错误说明'
    yield 'b'
g=g3()

try:
    print(next(g))  #a
    print(next(g))  #触发异常
except StopIteration as exc:
    result=exc.value
    print(result)
```
